### ISSUE TITLE
Assertion panic for every etw trace recorded with UIforETW

### ISSUE THREAD

**Issue by clemenswasser** [jrmuizel/etw-profiler#10]
I usually record my etw traces with [UIforETW](https://randomascii.wordpress.com/2015/04/14/uiforetw-windows-performance-made-easier/) and noticed that the latest version of etw-gecko recently began to panic on every etw trace I record (regardless of the settings in UIforETW).
The panic log:
```console
thread 'main' panicked at etw-reader\src\etw_types.rs:166:13:
assertion failed: (curr_prop.Flags.0 & PropertyStruct.0 == 0)
```
The assertion in question is this one (introduced in https://github.com/jrmuizel/etw-profiler/commit/efb99a78975be5e6e77ad8db6ef33312d1b0ae3f):
https://github.com/jrmuizel/etw-profiler/blob/27f7592052615157bb30a7fb030d4c59e6753ec9/etw-reader/src/etw_types.rs#L166
Reproduction:
- Record a short etw trace with UIforETW (Placed by default in `~/Documents/etwtraces`)
- Try to use etw-gecko e.g., `etw-gecko.exe <path_to_etl> explorer.exe`
- Observe the assertion panic

**Comment by jrmuizel** [comment]
I can reproduce this.
