### ISSUE TITLE
None main_thread_handle

### ISSUE THREAD

**Issue by clemenswasser** [jrmuizel/etw-profiler#8]
First and foremost, thank you so much for this amazing tool! 😄 
During a recent trace recording, I encountered a crash in `etw-gecko` with the following error message:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', etw-gecko\src\main.rs:877:159
```
To temporarily address this issue, I made modifications to the source code that allow `main_thread_handle` to be `None`. Additionally, I logged the `ProcessHandle`s associated with instances where `main_thread_handle` is `None`. The logged information is as follows:
```
[etw-gecko\src\main.rs:878] process.process_handle = ProcessHandle(
    28,
)
[etw-gecko\src\main.rs:878] process.process_handle = ProcessHandle(
    25,
)
[etw-gecko\src\main.rs:878] process.process_handle = ProcessHandle(
    22,
)
[etw-gecko\src\main.rs:878] process.process_handle = ProcessHandle(
    27,
)
[etw-gecko\src\main.rs:878] process.process_handle = ProcessHandle(
    17,
)
[etw-gecko\src\main.rs:878] process.process_handle = ProcessHandle(
    19,
)
```
Upon analyzing the trace, it appears that out of the 29 entries in the `processes` list, 6 processes contain a None value for their `main_thread_handle`. My question is whether this behavior is expected or if it indicates a bug?

**Comment by clemenswasser** [comment]
Even with the `main_thread_handle` issue "resolved" (I just don't emit the `UserTiming` markers). I get the following error in firefox profiler:
```
Uh oh, some unknown error happened in profiler.firefox.com.
Error: Unable to find a global track from the given pid..
Please report this issue to the developers, including the full error as displayed in the Developer Tools’ Web Console.
```

**Comment by jrmuizel** [comment]
I suspect this is probably a regression. Do you see the problem if you try using 6bf6e0e5866ea99b7d801ac4259afbe5a773102a?

**Comment by clemenswasser** [comment]
Yes, `etw-gecko` doesn't crash with that commit you mentioned, thanks!
But even with that commit, I get `Error: Unable to find a global track from the given pid..` when opening profiler.firefox.com

**Comment by jrmuizel** [comment]
Is it possible for you to share the etw file or steps to reproduce?

**Comment by clemenswasser** [comment]
My use case is profiling the typical CMake configuration phase (it's still pretty slow on Windows 😞).
I'm doing the following steps inside a "Developer Powershell for VS 2022" (vcvars, cl.exe must be in path):
```
# Clone CMake
git clone https://gitlab.kitware.com/cmake/cmake.git
# Configure CMake
cmake -G Ninja -B build-msvc-release -D CMAKE_BUILD_TYPE=RelWithDebInfo
# Build CMake
cmake --build .\build-msvc-release\

# Profile this invocation with UIforETW and "Fast sampling" enabled:
.\build-msvc-release\bin\cmake.exe -G Ninja -B build-perf -D CMAKE_BUILD_TYPE=Debug
```
For me, this produces an around 80 MB etl file. I then do:
```
etw-gecko.exe .\<produced_trace>.etl cmake.exe
profiler-symbol-server.exe .\gecko.json
```
What would be the best way to send my trace to you?

**Comment by jrmuizel** [comment]
You can share the trace on Google drive with jeff@mozilla.com

**Comment by jrmuizel** [comment]
One of the problems here is that thread ids are being reused and that's not handled well.
